#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           clawFlipOne,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           clawFlipTwo,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



void moveWheels(){
	//move motors
		if (vexRT[Ch3] > 0){
			motor[left] = 75;
			motor[right] = 75;
		}else if (vexRT[Ch3] < 0){
			motor[left] = -75;
			motor[right] = -75;
		}else if (vexRT[Ch4] > 0){
			motor[left] = 75;
			motor[right] = 0;
		}else if (vexRT[Ch4] < 0){
			motor[left] =  0;
			motor[right] = 75;
		}else {
			motor[left] = 0;
			motor[right] = 0;
		}
}

void flipClaw(){
	//flip cone thingie
		if (vexRT[Btn8D] == 1){
			motor[clawFlipOne] = -75;
			motor[clawFlipTwo] = -75;
		}else{
	  	motor[clawFlipOne] = 0;
			motor[clawFlipTwo] = 0;
		}
}

void autonomous(){
	//insert autonomous code here

}

task main()
{
	moveWheels();
	flipClaw();
}
